.vscode/settings.json, deno.jsonc, deno.lock, main.ts
`main.ts` は `src/` に入れてもいいかもしれない
=> feat: Hello World 実装の追加

.vscode/extensions.json
- VSCodeで開発するときに特定の拡張機能を推奨するファイルを追加
- Deno
=> VSCodeで推奨する拡張機能を追加

CONTRIBUTING.md
Notion のスタイルガイドを反映させたものを `CONTRIBUTING.md` として追加しました.
=> docs: CONTRIBUTING.md の追加

.github/ISSUE_TEMPLATE/bug_report.yml, SECURITY.md
=> docs: Security Policy の追加

.github/workflows/deno.yaml, deno.json
deno fmt, deno lint を実行する CI を追加しました. すべて一連のワークフローで完結します.
=> ci: Deno の CI を追加

.editorconfig, CONTRIBUTING.md
Notion スタイルガイド準拠の `.editorconfig` を追加しました.
=> chore: .editorconfig の追加

CONTRIBUTING.md
データベーススキーマのマイグレーション方法に関するドキュメントを`CONTRIBUTING.md`に追加しました。
機械翻訳したので文章が破綻しているかもしれません、文法の確認をお願いしたいです......
=> docs: add database migration documents in CONTRIBUTING.md

docs/api.yaml
Resolve PUL-64 OpenAPI Spec
Pulsate APIの定義をOpenAPI 3.0.3に従って行いました。  
Notionにあるドキュメントの内容をそのまま移しているだけなので、おかしい点があれば指摘をお願いしたいです
Swagger UIでの表示が正しくできることを確認しています
=> feat: add openapi schema

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
昨日行ったラベル整備に追随して Issue Template Form で使用されるラベル名を修正しました.
=> chore: Issue Template Form で使用されるラベル名を修正

.github/SECURITY_JA.md, SECURITY.md
=> docs: セキュリティポリシーの日本語版を追加

README.md
This PR adds about pulsate projects information to the README.md file.
The logo is not yet completed, so it is only temporarily added.
=> docs: Added about pulsate project to README.md

.hooks/pre-commit, deno.jsonc
Setup commit hooks.
Run `deno fmt` , `deno lint` when commit.
=> chore: setup commit hooks

.vscode/extensions.json
<!--
Thanks for submitting a pull request!
- If this pr is your frist contribution, read "CONTRIBUTING.md".:
https://github.com/approvers/pulsate/blob/main/.github/CONTRIBUTING.md
- Run `deno fmt` to format your code.
- If your PR is not finished, set it as "draft" PR.
See more: https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request
Explain the motivation behind this PR and change.
It is better to explain in detail and have a clear reason.
You can use keyword "Fixes #issue-number" to close issue automatically.
Please describe any additional information you would like to convey.
>
デフォルトではVSCodeは`.editorconfig`を読み込めないので推奨する拡張機能を追加する。
=> chore: VSCodeの推奨プラグインにEditorConfigを追加

deno.jsonc
This PR sets `deno task start` and `deno task dev`.
- `deno task start` is run `main.ts`
- `deno task dev` is run `main.ts` (watcher)
=> chore: add `start` and `dev` task

pkg/accounts/adaptor/repository/dummy.ts, pkg/accounts/model/repository.ts, pkg/accounts/service/register_service.ts, pkg/accounts/service/token_verify_service.ts
レポジトリの命名がスタイルに沿わない形になってるので修正しました.
=> fix: repository method naming

deno.jsonc
<!--
Thanks for submitting a pull request!
- If this pr is your frist contribution, read "CONTRIBUTING.md".:
https://github.com/approvers/pulsate/blob/main/.github/CONTRIBUTING.md
- Run `deno fmt` to format your code.
- If your PR is not finished, set it as "draft" PR.
See more: https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request
Explain the motivation behind this PR and change.
It is better to explain in detail and have a clear reason.
You can use keyword "Fixes #issue-number" to close issue automatically.
Please describe any additional information you would like to convey.
>
Add a version suffix to import path for npm package
=> fix(deps): fix import-map

deno.lock
=> chore(deps): update lockfile

.vscode/launch.json
Add VSCode debugger configuration. The program code and test code be debugged by the debugger.
It's need `vscode.deno` for execution.
=> test: add vscode debugger configuration `launch.json`

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/SECURITY_JA.md, .github/workflows/staging-apply.yaml, CONTRIBUTING.md, README.md, SECURITY.md, deployment.yaml, staging/variables.tf
=> docs: update github url

deno.jsonc, deno.lock, main.ts, pkg/accounts/adaptor/validator/schema.ts, pkg/accounts/mod.ts, pkg/accounts/router.ts
=> feat: API/バリデータの定義

pkg/accounts/service/editAccount.ts, pkg/accounts/service/etagGenerateVerify.test.ts, pkg/accounts/service/etagGenerateVerify.ts
Change function name to camelCase.
=> chore: change function name to camelCase

pkg/accounts/model/account.test.ts, pkg/accounts/service/resendToken.test.ts, pkg/accounts/service/resendToken.ts
=> feat: resend account verify code

pkg/accounts/model/account.test.ts, pkg/accounts/model/account.ts, pkg/accounts/service/editAccount.test.ts, pkg/accounts/service/etagGenerateVerify.test.ts, pkg/accounts/service/freeze.test.ts, pkg/accounts/service/register.test.ts, pkg/accounts/service/register.ts, pkg/accounts/service/silence.test.ts
アカウント名のバリデーションをテンプレートリテラルを使って行うようにしました
=> feat: Account name validation with template literal

lefthook.yml, package.json, pnpm-lock.yaml
Commit Hook is set. It is executed when a TypeScript, JavaScript, Markdown file is committed.
Prettier (Check) and ESLint are executed.
The Commit Hook uses [lefthook](https://github.com/evilmartians/lefthook). Unlike Husky, [it is configurable in YAML Format.](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md) Set [Linear](https://linear.app/pulsate/issue/PUL-139/) or [the official readme](https://github.com/evilmartians/lefthook/blob/master/README.md) for more details.
=> chore: setup commit hook

pkg/accounts/model/account.ts, pkg/accounts/service/authenticate.test.ts, pkg/accounts/service/authenticate.ts, pkg/accounts/service/tokenGenerator.test.ts, pkg/accounts/service/tokenGenerator.ts, pkg/id/mod.ts, pkg/time/mod.ts
=> feat: impl `AuthenticationService`

.github/workflows/node.yaml, .gitignore, package.json, pnpm-lock.yaml, vite.config.ts
- vitestを利用したカバレッジの生成
- カバレッジレポート(with codecov)
=> feat: Coverage report with Codecov

README.md
- Fixed several word errors.
- Unified GitHub Discussions with Pulsate repository, removed obsolete links.
=> docs: some corrections in `README.md`.

pkg/notes/model/note.test.ts, pkg/notes/model/note.ts
=> feat: define note model

eslint.config.js, pkg/accounts/service/editAccount.test.ts, pkg/accounts/service/etagGenerateVerify.test.ts, pkg/accounts/service/fetchAccount.test.ts, pkg/accounts/service/follow.test.ts, pkg/accounts/service/freeze.test.ts, pkg/accounts/service/silence.test.ts, pkg/accounts/service/unfollow.test.ts
- enable ESLint rule `@typescript-eslint/no-floating-promises`
- fix some errors in test files
=> fix: enable no-floating-promises

pkg/accounts/adaptor/repository/dummy.ts, pkg/notes/adaptor/repository/dummy.ts, pkg/notes/model/note.test.ts, pkg/notes/model/note.ts, pkg/notes/model/repository.ts
- `NoteRepository`の定義と実装
- `Note`モデルに不足していたメンバ変数の追加(`AuthorID`)
=> feat:  define and implement AccountRepository

pkg/accounts/service/accountVerifyToken.test.ts, pkg/accounts/service/accountVerifyToken.ts, pkg/accounts/service/register.test.ts, pkg/accounts/service/resendToken.test.ts
Change clock from an optional argument to a mandatory argument.
=> feat(account)!: change TokenVerifyService's arguments

pkg/accounts/service/accountVerifyToken.test.ts, pkg/accounts/service/register.test.ts, pkg/accounts/service/resendToken.test.ts, pkg/id/mod.ts
Add mock for Clock interface and change to use MockClock when testing
=> feat: add mock for Clock interface

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/adaptor/repository/dummy.ts, pkg/accounts/adaptor/repository/prisma.ts, pkg/accounts/model/account.ts, pkg/accounts/model/repository.ts, pkg/accounts/service/fetchAccount.test.ts, pkg/accounts/service/fetchAccount.ts, pkg/intermodule/account.ts, pkg/notes/adaptor/controller/note.ts, pkg/notes/adaptor/validator/schema.ts, pkg/notes/mod.ts, pkg/notes/router.ts, pkg/notes/service/fetch.test.ts, pkg/notes/service/fetch.ts
- ノート取得の実装
- FetchNoteServiceの実装とテスト
- NoteControllerへの実装追加
- APIスキーマの追加とルート定義、ハンドラ実装
- 足りないAccountModuleの機能追加
- `AccountModule.fetchAccountByID(id: ID<AccountID>)`の実装とテスト
=> feat: impl FetchNoteService and Controller, Handler

.github/CONTRIBUTING_JA.md, CONTRIBUTING.md, pkg/accounts/service/authenticate.test.ts
Add the naming guide defined in Pulsate Notion.
=> docs: addition of naming guide

.github/CONTRIBUTING_JA.md, CONTRIBUTING.md, package.json
- Added about generate Prisma Client in `CONTRIBUTING.md` and `CONTRIBUTING-JA.md`
- Added generate Prisma Client script
=> chore: Add generate Prisma Client script

pkg/accounts/service/resendToken.test.ts, pkg/notes/service/fetch.test.ts
Reset of the account repository for testing with `afterEach`
=> test: Reset account repository with `afterEach`

.github/workflows/auto-assign-pr.yaml, .github/workflows/check-pr-title.yaml
Add a workflow to check if the PR title complies with conventional commit.
=> ci: Add workflow to check PR titles for conventional commit 

pkg/notes/adaptor/controller/note.ts, pkg/notes/adaptor/validator/schema.ts, pkg/notes/mod.ts, pkg/notes/model/note.test.ts, pkg/notes/model/note.ts, pkg/notes/router.ts, pkg/notes/service/create.ts, pkg/notes/service/fetch.test.ts, pkg/notes/service/renote.test.ts, pkg/notes/service/renote.ts
close #16 
- `RenoteService`の実装
- `RenoteRoute`の定義とController,Handlerの実装
リノート可能か`renotable`の判定は最低限のものを除いてTimelineModuleに任せる方向で実装しています.
=> feat: リノートの実装

pkg/notes/model/bookmark.test.ts, pkg/notes/model/bookmark.ts
Add `Bookmark` model and test-case.
=> feat: add `Bookmark` model

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/mod.ts, pkg/accounts/service/authenticate.test.ts, pkg/accounts/service/authenticate.ts, pkg/accounts/service/authenticationTokenService.test.ts, pkg/accounts/service/authenticationTokenService.ts, pkg/accounts/service/editAccount.test.ts, pkg/accounts/service/editAccount.ts, pkg/accounts/service/etagService.test.ts, pkg/accounts/service/etagService.ts, pkg/accounts/service/register.test.ts, pkg/accounts/service/register.ts, pkg/accounts/service/resendToken.test.ts, pkg/accounts/service/resendToken.ts, pkg/accounts/service/verifyToken.test.ts, pkg/accounts/service/verifyToken.ts, pkg/notes/mod.ts, pkg/notes/service/fetch.test.ts
=> chore(accounts): 一部のクラスをリネーム

pkg/notes/model/repository.ts, pkg/notes/service/createBookmark.test.ts, pkg/notes/service/createBookmark.ts, pkg/notes/service/deleteBookmark.test.ts, pkg/notes/service/deleteBookmark.ts, pkg/notes/service/fetchBookmark.test.ts, pkg/notes/service/fetchBookmark.ts
- Bookmarkを作成するCreateBookmarkServiceの実装
- Bookmarkを削除するDeleteBookmarkServiceの実装
- Bookmarkを取得するFetchBookmarkServiceの実装
=> feat(notes/service): implement Create, Delete, FetchBookmarkService

pkg/notes/adaptor/controller/bookmark.ts
=> feat: 投稿ブックマークのControllerの実装

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/mod.ts, pkg/accounts/router.ts, pkg/intermodule/account.ts, pkg/notes/adaptor/controller/note.ts, pkg/notes/mod.ts, pkg/notes/service/fetch.test.ts, pkg/notes/service/fetch.ts
- Intermodule内でControllerをimportしている部分を削除
- FetchAccountService.fetchAccountのパラメータをnameからidに変更
- `GET /accounts/:name`が`GET /accounts/:id`に変更されました(破壊的変更
=> feat!: use hono rpc at AccountModule.fetchAccount

apidoc.ts, main.ts, package.json, resources/schema.json
Zodの定義から生成されるOASの定義をファイルとして出力できるようにしました.  
`pnpm docs:api`で生成できます(事前にビルドが必要)
=> feat: impl OAS API Document exporter

pkg/id/mod.ts
idパッケージ内で宣言されている `interface Clock` のメソッド `now(): bigint`の返り値が何かを説明するTSDocを追加.
=> feat: add return value description Clock.now in id package

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/mod.ts, pkg/accounts/service/edit.test.ts, pkg/accounts/service/edit.ts, pkg/accounts/service/fetch.test.ts, pkg/accounts/service/fetch.ts, pkg/accounts/service/fetchFollow.test.ts, pkg/accounts/service/fetchFollow.ts, pkg/accounts/service/register.test.ts, pkg/accounts/service/register.ts, pkg/notes/adaptor/controller/note.ts, pkg/notes/mod.ts, pkg/notes/service/create.test.ts, pkg/notes/service/create.ts, pkg/notes/service/fetch.test.ts, pkg/notes/service/fetch.ts
=> chore:  change redundant service name

resources/schema.json
#365 で変更が加わった最新の API Schema を追加します.
=> chore: add `localhost` servers schema

pkg/accounts/adaptor/repository/prisma.ts
- PrismaAccountRepositoryでPrismaが生成した型を使うように
=> feat: use prisma generated type at PrismaAccontRepository

pkg/accounts/service/etagService.ts
- ETag生成時にstringではなくfunctionが代入されていたのを修正
=> fix: ETag生成の実装ミスを修正

pkg/accounts/mod.ts, pkg/accounts/service/authenticationTokenService.ts, pkg/adaptors/authenticateMiddleware.ts, pkg/notes/mod.ts
- Honoのミドルウェアとしてアクセストークンを検証するように
- 検証成功したらハンドラに`AccountName`を渡すように
- ハンドラの中身は別Issueで修正します
=> feat: Require authorization token at handlers

pkg/drive/adaptor/repository/dummy.ts, pkg/drive/adaptor/repository/prisma.ts, pkg/drive/model/medium.ts, pkg/drive/model/repository.ts, pkg/drive/service/upload.test.ts, pkg/drive/service/upload.ts
- Replace `ID<MediumID>` to `MediumID`.
- NOTE: `MediumID` type def: `ID<Medium>`
none
=> feat: Replace `ID<MediumID>` to `MediumID`

pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/repository/prisma.ts, pkg/notes/mod.ts, pkg/notes/model/repository.ts, pkg/notes/service/create.test.ts, pkg/notes/service/create.ts, pkg/notes/service/renote.test.ts, pkg/notes/service/renote.ts
=> feat: impl attach media to note

main.ts, pkg/drive/adaptor/controller/drive.ts, pkg/drive/adaptor/repository/dummy.ts, pkg/drive/adaptor/validator/schema.ts, pkg/drive/mod.ts, pkg/drive/router.ts, pkg/drive/service/fetch.test.ts, pkg/drive/service/fetch.ts, pkg/drive/service/upload.test.ts, resources/schema.json
- 自分が作成したメディア一覧のエンドポイントの実装
- ハンドラで操作したアカウントのIDを取得してServiceにわたす部分は未実装です
- 別Issueで全ハンドラに対して修正します
=> feat: impl get account uploaded media handler,services

.github/PULL_REQUEST_TEMPLATE.md, AUTHORS.md, CONTRIBUTING.md, LICENSE, README.md, SECURITY.md
- リポジトリの Readme を更新
- ライセンス, リポジトリのコピーライトを更新
- Contributing Guide に Pulsate Specification へのリンクを追加
=> docs: Update repository documents

pkg/timeline/model/list.test.ts, pkg/timeline/model/list.ts
close #566 
- define list model
- list model tests
=> feat: define List model

pkg/accounts/adaptor/validator/schema.ts, pkg/accounts/router.ts, resources/schema.json
close #579 
- 空レスポンスをやめて204 No Contentを利用するように
- APIリファレンスの更新
=> fix: APIで空オブジェクトを返すのをやめた

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/router.ts, pkg/timeline/service/fetchList.test.ts, pkg/timeline/service/fetchList.ts, resources/schema.json
close #610 
- FetchAccountListServiceの実装
=> feat: implement FetchAccountListService

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/model/list.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts, pkg/timeline/service/editList.test.ts, pkg/timeline/service/editList.ts, resources/schema.json
=> feat: implement EditList API endpoint

pkg/notes/adaptor/controller/reaction.ts, pkg/notes/adaptor/presenter/reacton.ts, pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/validator/schema.ts, pkg/notes/mod.ts, pkg/notes/model/reaction.test.ts, pkg/notes/model/reaction.ts, pkg/notes/model/repository.ts, pkg/notes/router.ts, pkg/notes/service/createReaction.test.ts, pkg/notes/service/createReaction.ts, resources/schema.json
=> feat: 投稿にリアクションが付けられるようにする

pkg/accounts/adaptor/controller/account.ts, pkg/intermodule/account.ts, pkg/timeline/adaptor/controller/timeline.ts
=> refactor: use `AccountModuleFacade.fetchAccounts`

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/mod.ts, pkg/accounts/service/edit.test.ts, pkg/accounts/service/edit.ts, pkg/accounts/service/freeze.test.ts, pkg/accounts/service/freeze.ts, pkg/accounts/service/silence.test.ts, pkg/accounts/service/silence.ts
close #641 
- アカウントの凍結/サイレンスを管理者/モデレーターからのみ実行可能に
なし
=> feat: add actor permission check

pkg/accounts/testData/testData.ts, pkg/intermodule/account.ts, pkg/intermodule/timeline.ts, pkg/notes/mod.ts, pkg/notes/service/create.test.ts, pkg/notes/service/create.ts, pkg/timeline/service/push.ts
- 投稿したときにタイムライン/リストに配信するように
- テストデータを更新
- タイムライン or リストへの配信に失敗した場合でも投稿の戻り値はErrorにならないようにしています
=> feat: add test data, push note to home timeline

pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/repository/prisma.ts, pkg/notes/model/repository.ts, pkg/timeline/adaptor/repository/prisma.ts
close #502 
- 足りていなかったRepositoryを実装
- ReactionRepository
- ListRepository
- InActiveAccountRepositoryが未使用なので扱いをどうするかを検討する必要があります
- Prismaの出力するエラーをラップするのは別Issueにしようと思います (変更点が多くなりそうなため)
=> feat: PrismaによるRepositoryの実装をする

pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/repository/prisma.ts, pkg/notes/model/repository.ts, pkg/notes/service/fetch.test.ts, pkg/notes/service/fetch.ts
- fetchServiceにノートの複数取得メソッドを追加
- NoteRepositoryにも同様に追加
- 電車に乗りながら書いたのでミスがあるかもしれません.ちょっと入念に見てほしいかもしれないです
=> feat: ノートの複数取得メソッドをfetchServiceに追加

pkg/intermodule/account.ts, pkg/intermodule/note.ts, pkg/notes/model/repository.ts, pkg/notes/service/fetch.ts
close #721 
related #562 
- NotemoduleFacadeを実装
- ノートの添付ファイル、リアクションを取得できるように
ToDo: リノート時に元ノートに関する情報を取ってくる必要がありそう
=> feat: impl NoteModuleFacade

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts, pkg/timeline/service/list.test.ts, pkg/timeline/service/list.ts
close #562 
- ListTimelineServiceの実装
- controller,handler定義
controllerの実装がだいぶ非効率になっている気がしています(実際に動かないとわからないかもしれないですが...)
=> feat: Listタイムラインのノートを取得できるように

pkg/notes/adaptor/controller/reaction.ts, pkg/notes/adaptor/presenter/errors.ts, pkg/notes/mod.ts, pkg/notes/model/errors.ts, pkg/notes/model/note.ts, pkg/notes/router.ts, pkg/notes/service/create.ts, pkg/notes/service/createBookmark.ts, pkg/notes/service/createReaction.ts, pkg/notes/service/renote.test.ts, pkg/notes/service/renote.ts, resources/schema.json
close #697 
- Noteモジュールのカスタムエラー型を定義
- API側のエラーを詳細に書いた
=> feat: Noteモジュールでカスタムエラー型を使うように

pkg/timeline/adaptor/presenter/errors.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/adaptor/repository/valkeyCache.ts, pkg/timeline/mod.ts, pkg/timeline/model/errors.ts, pkg/timeline/router.ts, pkg/timeline/service/push.ts
close #699 
- タイムラインモジュールのエラー型の定義
- APIスキーマの変更
=> feat: タイムラインモジュールでカスタムエラー型を使うように

pkg/drive/adaptor/presenter/errors.ts, pkg/drive/adaptor/repository/prisma.ts, pkg/drive/mod.ts, pkg/drive/model/errors.ts, pkg/drive/router.ts, pkg/drive/service/fetch.ts, pkg/drive/service/upload.test.ts, pkg/drive/service/upload.ts
close #698 
- ドライブモジュールのエラー型を定義
- APIのエラーコードを定義
=> feat: define drive module custom error types

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/validator/timeline.ts
close #760 
- APIに不足していたメンバーを追加
- リアクション
- 添付ファイル
=> feat: add reactions,attachment_files to timeline api

pkg/intermodule/account.ts, pkg/intermodule/note.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/dummyCache.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/adaptor/repository/valkeyCache.ts, pkg/timeline/mod.ts, pkg/timeline/model/repository.ts, pkg/timeline/service/createList.ts, pkg/timeline/service/deleteList.ts, pkg/timeline/service/editList.ts, pkg/timeline/service/fetchList.ts, pkg/timeline/service/fetchMember.ts, pkg/timeline/service/home.ts, pkg/timeline/service/list.ts, pkg/timeline/service/noteVisibility.ts
close #772 
- タイムラインモジュールのDIでEtherを使うように
- 足りていないEtherの定義をしました
他モジュールのIntermoduleFacadeをEtherから使う部分がなくそのままでは動かなかったので新しくnewEtherする部分を書き足しています
=> refactor: use Ether/EtherSymbol in Timeline Module

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/presenter/errors.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/mod.ts, pkg/timeline/model/errors.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts, pkg/timeline/service/appendMember.test.ts, pkg/timeline/service/appendMember.ts
close #564 
- リストにメンバーを追加できるように
- メンバー削除のルーティング定義も同時に行いました
=> feat: リストにメンバーを追加できるように

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/service/removeMember.test.ts, pkg/timeline/service/removeMember.ts, resources/schema.json
close #565 
- RemoveListMemberServiceを実装
- APIスキーマを更新
=> feat: リストのメンバーを削除することができるように

CONTRIBUTING.md
- マイグレーションの節にあったgooseの記述を消してprismaのドキュメントを参照するように案内
日本語訳は別PRでやります
=> chore(docs): update contributing guide

main.ts, package.json, pkg/accounts/adaptor/logger.ts, pkg/accounts/mod.ts, pkg/drive/adaptor/logger.ts, pkg/drive/mod.ts, pkg/federation/adaptor/logger.ts, pkg/notes/adaptor/logger.ts, pkg/notes/mod.ts, pkg/timeline/adaptor/logger.ts, pkg/timeline/mod.ts, pnpm-lock.yaml, scripts/build.js
close #615 
close #614 
- ロガーの設定
- 仮でpretty printするようにしました
- ログを出力するように
- 実装されているすべてのエンドポイントで以下のエラーが発生した時にログを出力するように
- エラー発生時
- 内部エラー発生時(InternalError扱い)
=> chore: output log from all modules

pkg/notification/adaptor/repository/dummy/notification.test.ts, pkg/notification/adaptor/repository/dummy/notification.ts, pkg/notification/adaptor/repository/prisma/notification.ts, pkg/notification/model/notification.ts, pkg/notification/model/repository/notification.ts, prisma/migrations/20241216070132_add_notification_model/migration.sql, prisma/schema.prisma
close #875 
- NotificationRepositoryの定義と実装
- フィルターの指定にCursorを使うようにしました
=> feat: implement NotificationRepository

pkg/intermodule/account.ts, pkg/timeline/adaptor/controller/timeline.ts
close #923 
タイムラインでアバター/ヘッダー画像のURL，フォロー中/フォロワー数を正しく返せるように  
- Listタイムラインの取得処理だけgetAdditionalDataを呼んでいなかったのを修正
- Intermodule AccountModuleFacadeにメソッド追加
=> feat: fill timeline author avatar/header image urls, followed/following counts

pkg/intermodule/notification.ts, pkg/notification/service/create.test.ts, pkg/notification/service/create.ts
close #934 
- CreateNotificationServiceを実装しました
- Ether系定義 + Intermoduleでのexportも同時に行っています
=> feat: CreateNotificationServiceを実装

pkg/notes/mod.ts, pkg/notes/service/create.test.ts, pkg/notes/service/create.ts, pkg/notes/service/renote.test.ts, pkg/notes/service/renote.ts
Fixes #914.
参照等価でない関数である, 引数なしの `Date` コンストラクタの呼び出しを取り除き, `Clock` インターフェイスを実装したオブジェクトを注入するようにリファクタしました.
=> refactor(notes): Remove new Date

pkg/federation/model/__snapshots__/instance.test.ts.snap, pkg/federation/model/instance.ts
Fixes #913.
`Instance` クラスからプロパティ `updated` と, これを使用するメソッドを取り除きました.
=> fix(federation): Remove property updated

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/mod.ts, pkg/timeline/router.ts, pkg/timeline/service/fetchBookmark.test.ts, pkg/timeline/service/fetchBookmark.ts, resources/schema.json
close #605 
- ブックマーク(複数)取得を実装しました
- ノートの複数取得は専用のメソッドを実装するのではなくHomeTimeline取得時のメソッドを使っています
- ToDo: has_attachment/noNsfwの取得オプションには対応していません
=> chore: impl GET /timeline/bookmarks

pkg/notification/adaptor/repository/dummy/notification.ts, pkg/notification/adaptor/repository/prisma/notification.ts, pkg/notification/model/repository/notification.ts, pkg/notification/service/fetch.test.ts, pkg/notification/service/fetch.ts
close #946 
- FetchNotificationServiceを実装しました
- NotificationRepositoryでrecipientIDが何故かstringになっていたので修正
- ToDo: Notificationモジュールのエラーの定義をする
=> chore: impl FetchNotificationService

pkg/accounts/adaptor/repository/dummy/avatar.ts, pkg/accounts/adaptor/repository/dummy/header.ts, pkg/accounts/adaptor/repository/prisma/avatar.ts, pkg/accounts/adaptor/repository/prisma/header.ts, pkg/accounts/model/repository.ts, pkg/accounts/service/avatar.ts, pkg/accounts/service/header.ts, pkg/intermodule/account.ts, pkg/timeline/adaptor/controller/timeline.ts
close #1044
- 複数のアカウントのAvatar/Headerを一括取得できるようにしました．
- 主にTimelineからの利用を想定しています
=> chore: Avatar/Headerを複数取得できるようにした

pkg/accounts/mod.ts, pkg/accounts/testData/testData.ts
- **Update passphraseHash**
- **Apply dummyAccounts in development mode**
=> chore: Inject test account data for development mode

main.ts, resources/schema.json
close #1083 
- /v0/notificationのルーティングを読み込むように
- 自動生成のAPIリファレンスがアクセス出来ない状態になっていました
- APIドキュメントの更新
=> chore: add /notification route, update API document

.dockerignore, .github/workflows/hadolint.yaml, Dockerfile, compose.yaml, pkg/adaptors/valkey.ts
close #1088 
- Dockerfileを定義しました
- compose.ymlをresources/dockerからトップレベルに移動させ，環境変数等の設定項目を追加しました
- redisへの接続が決め打ちになっていたので，設定できるようにしました
- フォールバックでlocalhostを見に行くようにしています
- Actionsのhadolint.yamlに必要なさそうな項目があったので消しました
=> chore: setup dockerfile

pkg/notification/adaptor/controller/notification.ts, pkg/notification/adaptor/validator/schemas.ts, pkg/notification/mod.ts, pkg/notification/service/fetch.ts
close #1066 
- `GET /v0/notifications`を実装しました
- Controller/Handlerだけ実装されていなかったものです
- リノートの内容とリアクションの絵文字の取得は別のPRで対応しようと思います
- Controllerで取得するのではなくFetchNotificationService(のメソッド？)で取得するほうが良いのではないかと思っています
=> feat: impl GET /v0/notifications

pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/model/repository.ts, pkg/timeline/service/fetchConversation.test.ts, pkg/timeline/service/fetchConversation.ts
close #928 
- ダイレクト投稿を取得するServiceを実装しました
- APIの実装は別PRで行います
=> feat: ダイレクト投稿を取得できるようにした

biome.jsonc
- Update `biome.json` JSON schema version from `2.0.4` to `2.0.6`.
none
=> chore(config): update biome config JSON schema version to 2.0.6

pkg/accounts/router.ts, resources/schema.json
close #1145 
- Rename `DELETE /v0/accounts/:name/head` to `DELETE /v0/accounts/:name/header`
- update OpenAPI Spec
=> fix(api)!: Rename `DELETE /v0/accounts/:name/head` to `DELETE /v0/accounts/:name/header`

package.json, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/router.ts, pnpm-lock.yaml, resources/schema.json
- `@hono/zod-openapi`と`@asteasolutions/zod-to-openapi`が両方zodに依存しているが，zod v4対応がズレていて起動できなくなる問題を解決
- `zod-openapi`/`zod-to-openapi`が使うzodを`^4.0.0`にpeerDepsで指定しました
=> fix(deps): fix broken zod peer deps
