pulsate-dev/pulsate

.github/workflows/staging-apply.yaml
なぜかイメージ名がコピー元の oreorebot2 のままだったので修正しました. またイメージをビルドする時のディレクトリ (コンテキスト) の指定が抜けていたので追加しました.
=> ci: Fix to set context

.github/workflows/staging-apply.yaml, .github/workflows/staging-plan.yml, .gitignore, staging/.terraform.lock.hcl, staging/backend.conf, staging/main.tf, staging/terraform.tfvars, staging/variables.tf
- プロジェクト ID を渡すべき箇所で誤ってプロジェクト名を渡していたのを修正
- staging ディレクトリにて Terraform の初期化を実行
=> ci: Fix about permissions

.vscode/extensions.json, .vscode/settings.json, CONTRIBUTING.md
VSCode の拡張機能 [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) をプロジェクト (Workspace) 規定のプラグインに指定しました.
Markdown All in One が自動生成する Toc (目次) の対象見出しレベルを `2` から `6` の間に変更しました.
これはファイルのタイトルが目次に挿入されてしまうのを防ぐためです.
=> chore: Markdown All in One をプロジェクト規定の拡張機能に追加

.github/renovate.json
[pulsate-dev/renovate-conf](https://github.com/approvers/pulsate) を適用し, renovate をセットアップします. 
なお, pulsate-dev/renovate-conf は pulsate-dev 依存の設定があり, それらは Overwrite しています.
renovate が Deno をネイティブサポートしていないため, 正規表現で依存関係マネージャーを設定できる `regexManagers` を使用し, Deno を無理やり対応させています.
1. 参考: [Renovate で Deno の依存関係を自動で更新する - blog.s2n.tech](https://blog.s2n.tech/articles/renovate-deno)
2. 参考: https://github.com/renovatebot/renovate/issues/6237
=> chore: renovate のセットアップ

pkg/accounts/adaptor/repository/dummy.ts, pkg/accounts/service/freeze_service.test.ts, pkg/accounts/service/freeze_service.ts, pkg/accounts/service/register_service.test.ts, pkg/accounts/service/register_service.ts, pkg/accounts/service/silence_service.test.ts, pkg/accounts/service/silence_service.ts
Add `SilenceService` and `FreezeService`.
- `SilenceService` puts an account into silence. (Accounts under silencing will not be able to post, etc...)
- `FreezeService` puts an account into freeze. (Accounts that are frozen will not be able to access the Pulsate instance itself.)
https://github.com/approvers/pulsate/blob/9214614389258917896de85fe2a30bf6637394ab/docs/api.yaml#L148-L169
=> feat: add `SilenceService` and `FreezeService`

.vscode/settings.json
Set the default code formatter of VSCode to `deno fmt`.
Useful for the environments that use Prettier by default.
=> chore: set default code formatter to `deno fmt`

deno.jsonc, deno.lock, pkg/accounts/service/tokenVerify.test.ts, pkg/accounts/service/tokenVerify.ts
`26,171,156,60,129,175,29,202,111,157,110,229,40,151,46,128,146,111,101,38,184,211,211,227,198,46,200,252,225,153,188,9` というような形式で(Uint8Arrayそのままの形式で)出力されるのをBase64で出力するように修正しました
=> fix(bug): wrong format verify token

pkg/accounts/model/account.test.ts
おそらくDenoのバグで`\'`というような書き方がエラーになるので修正しました
=> fix: replace single quote to full-width apostrophe

.github/workflows/pr.yaml
Add pull-request workflow (GitHub Actions) to the project.
Automatically assigns a PR creator when the Assign field is empty.
=> ci: add pull-request workflow

.github/CONTRIBUTING_JA.md, .vscode/extensions.json, .vscode/settings.json, CONTRIBUTING.md, README.md
The replacement of Deno with Node.js in the documentation and VSCode extension configuration was not completed.
This pull request completes the replacement.
=> chore: Replace missing Node.js settings

pkg/accounts/service/editAccount.test.ts, pkg/accounts/service/etagGenerateVerify.test.ts, pkg/accounts/service/fetchAccount.test.ts, pkg/accounts/service/freeze.test.ts, pkg/accounts/service/silence.test.ts
Mock accounts used in almost all test cases are now created in-memory.
=> test: replace `RegisterService` to `InMemoryAccountRepository`

pkg/accounts/adaptor/repository/dummy.ts, pkg/accounts/adaptor/repository/prisma.ts, pkg/accounts/model/account.test.ts, pkg/accounts/model/account.ts, pkg/accounts/service/accountVerifyToken.test.ts, pkg/accounts/service/accountVerifyToken.ts, pkg/accounts/service/authenticate.test.ts, pkg/accounts/service/authenticate.ts, pkg/accounts/service/editAccount.test.ts, pkg/accounts/service/editAccount.ts, pkg/accounts/service/fetchAccount.test.ts, pkg/accounts/service/follow.ts, pkg/accounts/service/freeze.test.ts, pkg/accounts/service/register.test.ts, pkg/accounts/service/register.ts, pkg/accounts/service/resendToken.ts, pkg/accounts/service/sendNotification.ts, pkg/accounts/service/silence.test.ts, pkg/accounts/service/unfollow.ts, pkg/id/mod.test.ts, pkg/id/mod.ts, pkg/password/mod.test.ts, pkg/password/mod.ts
Sometimes methods in the interfaces/classes are not compliant to the coding style. So this refactors method names like as:
- Make method names camelCase
- Make get-accessors into getters
It seems that the account model definition is lacking domain-specific responsibilities. So it may be needed to improve with appending more functional methods.
=> refactor: Improve method names

main.ts, pkg/notes/adaptor/controller/note.ts, pkg/notes/adaptor/validator/schema.ts, pkg/notes/mod.ts, pkg/notes/router.ts, pkg/notes/service/create.test.ts, pkg/notes/service/create.ts
- `CreateNoteService`の実装とテスト
- `POST /notes`のスキーマ定義/コントローラー実装/エンドポイント実装
Schemaでz.dateを使おうとするとエラーになる謎の不具合に遭遇しました.  
調査はしますが現状はstringに書き直しています.
=> feat: impl create note API endpoint

LICENSE
The license name in the `LICENSE` was still `Approvers`, so it has been changed to `pulsate-dev`.
=> chore: fix License name

package.json
`pnpm run clean` does not work as expected, and the `rm` command does not work correctly on Windows OS, which is different from macOS and Linux. 
The `-force` option exists in `rm` on Windows OS, but it is different from `-f` in `rm` on Unix, so the `-f` option has been removed from `clean` scripts to work correctly on Windows OS.
=> chore: fix `clean` script

eslint.config.js, package.json, pnpm-lock.yaml
`eslint.config.js` への修正です. 特に `.languageOptions.globals` への変更ですが, `.ignores` と `.files` の glob が気になったのでこれにも変更を加えています.
N/A
=> chore: fix eslint configuration

build.js, package.json, pnpm-lock.yaml, tsconfig.json
`package.json` の `build` スクリプトの置き換えを行います.
- 旧 `build` スクリプトを `check` として残してあります
- 中括弧展開構文を使っているので bash 以外の環境下で動作するか不明です
- glob 展開は esbuild が行っています
=> chore: replace `build` script

.github/CODEOWNERS
The error is due to a member who has already left the team and is listed in the `CODEOWNER` file.
I removed the IDs of the departed members, switched to the method of specifying the Org Team directly, and removed @laminne from the code owner of all source code files.
=> chore: fix Codeowner error

vite.config.ts
Restrict Coverage measurement to `pkg/` and exclude unnecessary files such as `main.ts`, `build.js`, etc.
See also: https://linear.app/pulsate/issue/DEV-174/
=> test: restrict coverage measure to the `pkg/` dir only

.github/CONTRIBUTING_JA.md, CONTRIBUTING.md
Fixed `CONTRIBUTING.md`, #237 , because of limited permission to use `lowercase` in file names.
=> docs: allow filename casing `lowercase`

.github/workflows/ci.yaml
Upgraded `pnpm/action-setup`.
It now works with Node.js v16 to v20.
=> ci: bump `pnpm/action-setup` v2 to v3

.github/CONTRIBUTING_JA.md, CONTRIBUTING.md
Deno content forgotten during Node.js migration has been removed from the Contributing Guide
=> docs: Remove remaining Deno content from Contributing Guide

pkg/accounts/adaptor/repository/prisma.ts, prisma/schema.prisma
- prisma.schemaに記述されているモデル名およびフィールドをPrismaの命名規則に沿ったものに変更(Model: PascalCase, field: camelCase)
- 変更に伴い，PrismaClientに生成されるモデル名およびフィールドが変更されたため，`accounts/adaptor/repository/prisma.ts`を修正
- DB自体への変更はないため，マイグレーションは行っていません．
=> refactor: change prisma.schema to follow naming convention

pkg/accounts/service/fetchAccountFollow.test.ts, pkg/accounts/service/fetchAccountFollow.ts
`FetchAccountFollowService` を追加します. `ID<AccountID>` のみでなく `AccountName` でも取得できるよう拡張しています.
- `/* inferred */` の部分, きちんと型宣言した方が良いですか？
- `AccountName` を使えるようにする拡張, 要る？
=> feat: add `FetchAccountFollowService`

.github/workflows/check-pr-title.yaml
Add a comment to prompt correction when the CI that checks if the title complies with Conventional Commits fails.
=> ci: add comment pr step

pkg/accounts/service/editAccount.test.ts, pkg/accounts/service/editAccount.ts
- EditAccountServiceがAccountRepositoryのEditメソッドを使い，データストアの値を書き換えるように
- テストケースのリファクタ
=> feat(EditAccountService): changed edit method to update repository

.github/workflows/ci.yaml
`pnpm/action-setup@v3` は `version` での指定を外すと package.json の `packageManager` を見てバージョンを設定するようです.
Pulsate では CI 上で pnpm が最新版に固定されてしまい lockfile でエラーが発生していたのでこの指定を外し `packageManager` の値を見るようにします.
=> ci: fix pnpm version issue

.github/PULL_REQUEST_TEMPLATE.md
=> chore: fix typo, outdated content at PR template

package.json, pkg/accounts/mod.ts, pkg/intermodule/account.ts
- Hono RPCモードをIntermoduleの`AccountModule`クラスで利用するように
ToDo: コンストラクタ内でHono Clientを初期化する方法を探す  
ToDo: `AccountModule.fetchAccountByID`の実装を考える
=> feat: use hono rpc mode in intermodule interfaces

pkg/notes/adaptor/repository/dummy.ts, pkg/notes/model/repository.ts
BookmarkRepositoryにおけるcreate, findByID, deleteByIDが
- Bookmarkされた投稿のID(noteID)
- BookmarkしたアカウントのID(accountID)
を受け取り，処理するように修正しました．
=> fix(notes/repository/BookmarkRepository): BookmarkRepositoryの型定義およびダミー実装の修正

main.ts
- 自動生成されるOpenAPI Docsにserversの項目を追加(コード生成機でのエラーを解消できるように)
=> fix: add servers to openapi spec documentation

pkg/accounts/adaptor/repository/dummy.ts, pkg/accounts/adaptor/repository/prisma.ts, pkg/accounts/mod.ts, pkg/accounts/model/repository.ts, pkg/accounts/service/authenticate.ts, pkg/accounts/service/authenticationTokenService.ts, pkg/accounts/service/editAccount.ts, pkg/accounts/service/etagService.ts, pkg/accounts/service/fetchAccount.ts, pkg/accounts/service/fetchAccountFollow.ts, pkg/accounts/service/follow.ts, pkg/accounts/service/freeze.ts, pkg/accounts/service/register.ts, pkg/accounts/service/resendToken.ts, pkg/accounts/service/sendNotification.ts, pkg/accounts/service/silence.ts, pkg/accounts/service/unfollow.ts, pkg/accounts/service/verifyToken.ts, pkg/id/mod.ts, pkg/password/mod.ts
My library mini-fn has a module `Ether`, the dependency injection helper. It uses `Symbol`s to determine what are resolved or not.
At first, I'd replaced manual DI in `accounts` package with Ether as experiment. It would be nicer than calling their constructor of services directly.
=> refactor: Replace DI in accounts pkg with Ether

pkg/notes/adaptor/controller/bookmark.ts, pkg/notes/service/createBookmark.test.ts, pkg/notes/service/createBookmark.ts
- `BookmarkController.createBookmark`メソッドがNoteモデルを返すように変更
- `CreateBookmarkService`がコンストラクタにNoteRepositoryを要求するよう変更
- `CreateBookmarkService.handle`メソッドにブックマーク対象ノートが見つからなかったときの処理を追加
- 追加した処理に対応するテストコードの追加
=> fix(notes/bookmark): return target note model

pkg/drive/model/medium.ts, pkg/drive/model/repository.ts
- メディアのドメインモデルの定義
- MediaRepositoryの定義
- S3互換ストレージでどのようにオブジェクトを特定するのかが不明だったのでpath等は追加していません
=> feat: define medium model, media repository

.github/renovate.json, .github/workflows/auto-assign-pr.yaml
Cherry-picked from https://github.com/pulsate-dev/pulsate.dev/commit/3fbbeb65f2c9079bb93514b8b79ba9547270d49d, https://github.com/pulsate-dev/pulsate.dev/commit/afb7b6a97c3c78a5c446bcb53fe1186558dcd854
Removed outdated renovate settings and fixed an auto-assign workflow that prevented renovate from being assigned.
=> chore: remove out-of-date renovate config

pkg/notes/adaptor/controller/bookmark.ts, pkg/notes/adaptor/validator/schema.ts, pkg/notes/mod.ts, pkg/notes/router.ts
=> feat(notes): implement bookmark API handler

main.ts, pkg/notes/adaptor/repository/prisma.ts, pkg/notes/mod.ts
- `PrismaNoteRepository`の実装
- `PrismaBookmarkRepository`の実装
- Note系APIで動作モードを認識してPrisma or InMemoryを使うかの変更を可能に
- ToDo: PrismaSchemaにいくつかの定義抜け(Note)があるのを解決する
- ToDo: 論理削除されているレコードを自動で除外するPrismaのミドルウェアの実装
=> feat: add note/bookmark Prisma Repository implement

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/adaptor/validator/schema.ts, pkg/accounts/mod.ts, pkg/accounts/router.ts, pkg/intermodule/account.ts, pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts, pkg/timeline/service/account.test.ts, pkg/timeline/service/account.ts, pkg/timeline/service/accountNotes.test.ts, pkg/timeline/service/noteVisibility.test.ts, pkg/timeline/service/noteVisibility.ts
- AccountTimelineServiceの実装 (アカウントタイムライン取得の実装)
- NoteVisibilityServiceの実装 (可視性チェックの実装)
- フォロー/フォロワー情報の取得のAPI実装 (Accountモジュール)
- Intermodule::AccountModule へのインタフェース追加
=> feat: Account Timeline

pkg/notes/adaptor/controller/bookmark.ts, pkg/notes/adaptor/controller/note.ts, pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/repository/prisma.ts, pkg/notes/model/bookmark.test.ts, pkg/notes/model/bookmark.ts, pkg/notes/model/note.test.ts, pkg/notes/model/note.ts, pkg/notes/model/repository.ts, pkg/notes/service/create.ts, pkg/notes/service/createBookmark.test.ts, pkg/notes/service/createBookmark.ts, pkg/notes/service/deleteBookmark.test.ts, pkg/notes/service/deleteBookmark.ts, pkg/notes/service/fetch.test.ts, pkg/notes/service/fetch.ts, pkg/notes/service/fetchBookmark.test.ts, pkg/notes/service/fetchBookmark.ts, pkg/notes/service/renote.test.ts, pkg/notes/service/renote.ts, pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/model/repository.ts, pkg/timeline/service/account.test.ts, pkg/timeline/service/noteVisibility.test.ts
- `ID<NoteID>`を`ID<Note>`に置き換えました.
=> fix: Replace ID<NoteID> to ID<Note>

main.ts, pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/dummy.test.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts, pkg/timeline/service/createList.test.ts, pkg/timeline/service/createList.ts, resources/schema.json
close #559 
- アカウントリストタイムラインを作成できるように
- Serviceの実装
- APIエンドポイントの定義と実装
- Controllerの追加
- APIスキーマの更新
- Timelineとパスが違う(`/timeline`/`/lists`)が、機能的に一緒なのでTimelineモジュールに置きました
- Controller等の実装もまとめています
- `ownerId`はダミー値を入れています (maybe fixed by #511 )
=> feat: impl CreateList API Endpoint

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/mod.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts, pkg/timeline/service/deleteList.test.ts, pkg/timeline/service/deleteList.ts, resources/schema.json
close #561 
- アカウントリストタイムラインの削除
- `DeleteListService`の実装 c4dfa63d96d94e3e16d0cfd84525dc3f7a790b91
- APIエンドポイントの定義・実装 c93ff897852cd0691fcf24cfea5d372ce2cb38ef b2e5739cc4ed61cb11df4e420d94f5493e7e4b81
- `DeleteListService`をControllerの依存関係に追加 b0e3cfbc756d321b60db4b3aefe51a5cc5abef2f
- APIスキーマの更新
=> feat: implement DeleteList API endpoint

pkg/accounts/adaptor/repository/dummy.test.ts, pkg/accounts/adaptor/repository/dummy.ts, pkg/accounts/adaptor/repository/prisma.ts, pkg/accounts/model/repository.ts, pkg/accounts/service/fetch.test.ts, pkg/accounts/service/fetch.ts, pkg/intermodule/account.ts, pnpm-lock.yaml
close #587 
- アカウントを複数取得する`fetchAccounts`の実装
- 内部用のメソッドなのでAccountModuleFacadeから呼び出せるように
=> feat: アカウントの複数一括取得の実装

pkg/accounts/testData/testData.ts, pkg/intermodule/account.ts, pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/router.ts, pkg/timeline/service/fetchMember.test.ts, pkg/timeline/service/fetchMember.ts, pkg/timeline/service/noteVisibility.test.ts, pkg/timeline/service/push.test.ts, pkg/timeline/testData/testData.ts, resources/schema.json
close #563 
- リストメンバー(assignees)を取得できるエンドポイントの実装
- APIリファレンスの更新
- spec.pulsate.devにはドキュメントがなかった(定義漏れ？)ので後で追加します
=> feat: impl fetch list members

pkg/timeline/mod.ts, pkg/timeline/router.ts
close #594 
- #549 で不要になったルート/スキーマ定義の削除
=> fix: remove unnecessary routes

pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/dummyCache.ts, pkg/timeline/adaptor/repository/valkeyCache.ts, pkg/timeline/model/repository.ts, pkg/timeline/service/fetchSubscribed.test.ts, pkg/timeline/service/fetchSubscribed.ts, pkg/timeline/service/noteVisibility.test.ts, pkg/timeline/service/noteVisibility.ts, pkg/timeline/service/push.test.ts, pkg/timeline/service/push.ts
close #571
- ノートをリストに配信できるようにした
- ホームタイムラインへの配信と同時にリストにも配信するようにしています
- テストケースの追加も行なっています
- ホームタイムラインへは配信できたが、リストには配信できなかったケースのハンドリングは実装していません
- 呼び出し側で工夫するしかなさそう
=> feat: impl push note to list

pkg/accounts/adaptor/controller/account.ts, pkg/drive/testData/testData.ts, pkg/notes/adaptor/controller/bookmark.ts, pkg/notes/adaptor/controller/note.ts, pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/validator/schema.ts, pkg/notes/mod.ts, pkg/notes/service/create.test.ts, pkg/notes/service/fetch.test.ts, pkg/notes/service/fetch.ts, pkg/notes/service/renote.test.ts, resources/schema.json
related #604 
related pulsate-dev/specification#9
- Note APIで、Attachmentの情報を返すようにしました
- API Docを更新
- Note APIのみ変更しています
- Timelineモジュール用にAttachmentを取得する処理はNoteモジュール用と事情(最大取得ノート数)が違うためです
- Timeline: 最大20ノート / Note: 1ノート
=> feat: NoteのAttachmentを返すように

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/mod.ts, pkg/accounts/service/edit.test.ts, pkg/accounts/service/edit.ts
related #608 
- `AccountModule::EditService#isAllowed`を追加
- 操作者(`Actor`)と操作する対象を受け取り、操作が可能かどうかを判定
- 必要なテストを追加
=> feat: アカウントロールなどによるアクセス制御の実装

pkg/drive/service/upload.test.ts, pkg/drive/service/upload.ts
`UploadMediaService` で `sharp` による不必要な再圧縮がかかっていたのでこれを削除した.
これに伴い `blurhash` のハッシュ値が変化したため, 該当するテストも合わせて修正した.
ImageMagick を使用し再圧縮前後で画像データの比較を目視と数値比較により行ったが, そもそも画像は WebP Lossy なこともあり, 再圧縮前後で意図しない有意な差は発見されなかった. 以下に再圧縮前後の画像データを `identify` に通した結果の diff を残しておく (ハイライトするために `<details>` で綴じなかった. 長いのはご容赦).
```diff
2c2
<   Filename: /tmp/before.webp
---
>   Filename: /tmp/after.webp
24c24
<       mean: 132.16 (0.518273)
---
>       mean: 132.107 (0.518069)
26,29c26,29
<       standard deviation: 87.7134 (0.343974)
<       kurtosis: -1.53583
<       skewness: -0.213171
<       entropy: 0.96809
---
>       standard deviation: 87.6616 (0.343771)
>       kurtosis: -1.53664
>       skewness: -0.212579
>       entropy: 0.968413
33c33
<       mean: 129.538 (0.507991)
---
>       mean: 129.671 (0.508515) …
```
=> fix: 不必要な再圧縮を削除

pkg/accounts/testData/testData.ts, pkg/notes/mod.ts, pkg/notes/service/renote.test.ts, pkg/notes/service/renote.ts
close #606 
- ノートがリノートできるかどうかをチェックするように
- 元ノートより公開範囲を広く設定した場合にエラーになるように
- テストの追加
- アカウントの権限チェック
- テストデータの追加と、ファクトリ関数の実装
アカウントの権限チェック(サイレンスされている時はPUBLICを選択できないようにする など)をCreateNoteServiceにも実装する必要がありそう
=> feat: ノートがリノート可能であるかをチェックするように

pkg/notes/adaptor/controller/note.ts, pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/repository/prisma.ts, pkg/notes/adaptor/validator/schema.ts, pkg/notes/mod.ts, pkg/notes/model/reaction.ts, pkg/notes/model/repository.ts, pkg/notes/service/fetch.test.ts, pkg/notes/service/fetch.ts, resources/schema.json
close #701 
- APIエンドポイントの修正
- ノート取得時にリアクションを取得できるように
- APIスキーマ定義の更新
- AttachmentのPrismaRepositoryで、シリアライズが壊れていたのを修正
なし
=> feat: return reactions GET /notes/:id ,fix broken serializer

pkg/accounts/adaptor/captcha/turnstile.ts, pkg/accounts/adaptor/presenter/errors.ts, pkg/accounts/adaptor/repository/dummy.ts, pkg/accounts/adaptor/repository/prisma.ts, pkg/accounts/mod.ts, pkg/accounts/model/errors.ts, pkg/accounts/router.ts, pkg/accounts/service/authenticate.ts, pkg/accounts/service/edit.ts, pkg/accounts/service/fetch.ts, pkg/accounts/service/fetchFollow.ts, pkg/accounts/service/follow.ts, pkg/accounts/service/freeze.ts, pkg/accounts/service/resendToken.test.ts, pkg/accounts/service/resendToken.ts, pkg/accounts/service/silence.ts, pkg/accounts/service/unfollow.ts, pkg/accounts/service/verifyToken.ts, resources/schema.json
close #696 
- Accountモジュール内で必要なエラー型を定義
- Prismaのエラーは一部のみパースするように
- APIエンドポイントが返すエラーコードを定義してスキーマを更新
- ほぼ全てのエンドポイントが(specificationで定義されている)エラーコードを適切に返すようになりました
Prismaのエラーは完全に内部表現にできなかったので、別Issueで対応した方が良いかもしれません(自分では判断できず)
=> feat: Accountモジュールのエラー型を定義してそれを使うように

pkg/adaptors/valkey.ts, pkg/intermodule/timeline.ts, pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/dummy.test.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts, pkg/timeline/service/home.ts
- ホームタイムラインのcontroller/handler実装をした
- PrismaRepository使用時に取得が壊れる問題を修正
- いくつかのRoute/Schema定義を分離して共通化した
PrismaTimelineRepository.getHomeTimelineからfilterを消しました  
理由:
- noNSFW/hasAttachmentの項目は未実装(後回し)
- beforeIDはIDを投入する前(≒ ServiceやValkeyCache)で決定して投入すべきなため
- HomeTimelineServiceの実装を改善して正しくbeforeIDが動作するようにしました
=> feat: home timeline controller/handler implementations

pkg/notes/adaptor/controller/reaction.ts, pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/repository/prisma.ts, pkg/notes/mod.ts, pkg/notes/router.ts, pkg/notes/service/deleteReaction.test.ts, pkg/notes/service/deleteReaction.ts, resources/schema.json
close #776 
- リアクションを解除できるように (`DELETE /notes/:id/reaction`
- Repositoryで、リアクション解除を論理削除->物理削除に変更しました
- noteIDとaccountIDの複合主キーなので、論理削除すると1回しかつけられなくなってしまうため
=> feat: リアクションを解除できるように

pkg/timeline/service/push.test.ts, pkg/timeline/service/push.ts
close #781 
- 投稿した本人のホームタイムラインにノートを配信するようにしました
- Caramelで正しく動作することを確認済み(投稿後のタイムライン自動更新も含め)
=> feat: push note to author's home timeline

pkg/adaptors/env.ts, pkg/drive/adaptor/repository/dummy.ts, pkg/drive/adaptor/repository/prisma.ts, pkg/drive/mod.ts, pkg/drive/service/fetch.ts, pkg/intermodule/account.ts, pkg/intermodule/note.ts, pkg/intermodule/timeline.ts, pkg/notes/adaptor/repository/dummy.ts, pkg/notes/adaptor/repository/prisma.ts, pkg/notes/mod.ts, pkg/notes/service/create.ts, pkg/notes/service/createBookmark.ts, pkg/notes/service/createReaction.ts, pkg/notes/service/deleteBookmark.ts, pkg/notes/service/fetchBookmark.ts, pkg/notes/service/renote.ts, pkg/timeline/mod.ts
close #788 
- Noteモジュール、DriveモジュールのDIでEtherを使うようにしました
- Intermoduleで公開されるEtherがモードに関係なくプロダクション用のものを使っていたのでそれをモードによって切り替えられるようにしました
=> refactor: Note/DriveモジュールのDIでEtherを使うようにした

pkg/adaptors/valkey.ts, pkg/intermodule/timeline.ts, pkg/timeline/mod.ts
close #777 
- valkey(redis)のクライアント初期化をproductionモード時のみ行うように
- Intermodule::TimelineModuleの初期化でモードを見てprisma/dummyを切り替えるように
=> fix: valkey client to be initialized only when needed

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/mod.ts, pkg/accounts/router.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/service/account.ts, resources/schema.json
close #785 
- `GET /accounts/:id`を`GET /accounts/:identifier`に変更
- IDまたはNameで取得できるように
- APIドキュメントの更新
- PrismaRepositoryの実装ミスで投稿を取得できない問題を修正
- 同様の実装が数箇所あるはずなので別の箇所についてはIssueを立てて対処します
=> feat: アカウントをID/Name両方で取得できるように

pkg/id/mod.ts, pkg/notes/service/create.test.ts, pkg/timeline/adaptor/repository/dummyCache.ts, pkg/timeline/adaptor/repository/valkeyCache.ts, pkg/timeline/model/repository.ts, pkg/timeline/service/list.test.ts, pkg/timeline/service/push.test.ts, pkg/timeline/service/push.ts
close #801 
- リスト/ホームタイムラインのキャッシュを300件までに制限するように
- ノートのソートに使う要素をCreatedAtからIDに
- テスト用repositoryでリストのキャッシュを正常に行えるように
=> feat: Added cache retention limit to list/home timeline

pkg/accounts/adaptor/repository/dummy/verifyToken.ts, pkg/accounts/adaptor/repository/prisma/prisma.ts, pkg/accounts/model/repository.ts, pkg/accounts/service/verifyToken.test.ts, pkg/accounts/service/verifyToken.ts
close #850 
- アカウントの有効化を実装
- 適切にメールアドレス検証トークンを削除できるように
- いくつかの部分で Promise.resolveを使わないように
=> feat: impl account activation

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/dummy.test.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/mod.ts, pkg/timeline/model/errors.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts
- HomeTimelineでそれ以降(新しい)の投稿を取得できるように
=> feat: HomeTimelineでafterIDを使ってページネーションできるように

pkg/notification/model/__snapshots__/notification.test.ts.snap, pkg/notification/model/notification.test.ts, pkg/notification/model/notification.ts
close #874 
- Notificationモデルの定義
- Announceモデルはv0.1では取り敢えずやらないことにします
=> feat: define Notification model

.vscode/settings.json, pkg/accounts/adaptor/controller/account.ts, pkg/accounts/adaptor/validator/schema.ts, pkg/accounts/mod.ts, pkg/accounts/service/authenticate.test.ts, pkg/accounts/service/authenticate.ts, pkg/accounts/service/authenticationTokenService.test.ts, pkg/accounts/service/authenticationTokenService.ts, pkg/drive/mod.ts, pkg/notes/mod.ts, pkg/timeline/mod.ts
close #906 
- 認証トークンのペイロードに`refreshToken`を追加
- `POST /login`から`refresh_token`を削除
- AuthenticationTokenService内部でClockを持つように
- それに伴うDI周りの更新
=> fix!: 認証トークンにリフレッシュトークンを含むようにした

pkg/accounts/adaptor/controller/account.ts, pkg/accounts/adaptor/validator/schema.ts, pkg/accounts/mod.ts, pkg/accounts/model/errors.ts, pkg/accounts/router.ts, pkg/accounts/service/authenticate.test.ts, pkg/accounts/service/authenticationTokenService.test.ts, pkg/accounts/service/authenticationTokenService.ts, pkg/adaptors/authenticateMiddleware.ts, pkg/drive/mod.ts, pkg/notes/mod.ts, pkg/timeline/mod.ts, resources/schema.json
close #907 
- 認証トークンを更新できるように
- `POST /refresh`の実装
- `POST /login`から`refresh_token`を削除
- APIドキュメントの更新
=> feat: 認証トークンを更新できるように

pkg/accounts/mod.ts, pkg/accounts/service/follow.test.ts, pkg/accounts/service/follow.ts, pkg/accounts/service/register.test.ts, pkg/accounts/service/register.ts
Fixes #912.
参照等価でない関数である, 引数なしの `Date` コンストラクタの呼び出しを取り除き, `Clock` インターフェイスを実装したオブジェクトを注入するようにリファクタしました.
=> refactor(accounts): Remove new Date

pkg/timeline/mod.ts, pkg/timeline/service/createList.test.ts, pkg/timeline/service/createList.ts
Fixes #915.
参照等価でない関数である, 引数なしの `Date` コンストラクタの呼び出しを取り除き, `Clock` インターフェイスを実装したオブジェクトを注入するようにリファクタしました.
=> refactor(timeline): Remove new Date

main.ts, pkg/accounts/router.ts, pkg/drive/router.ts, pkg/notes/router.ts, pkg/timeline/router.ts
close #909 
- すべてのAPIエンドポイントのパスを`/`直下から`/v0`に変更しました．
- specでは`/api/v0`と定義しましたが，特にそうする必要はなさそうなのでひとまずこうしています
- `/api`とつけたのはActivityPubなどで必要なエンドポイント名やフロントエンドと同居させる場合の競合の回避を意図したものです
=> feat!: change API endpoint paths from /moduleName to /v0/moduleName (API versioning)

pkg/adaptors/authenticateMiddleware.ts
close #1062 
- 認証を強制している && トークンが指定されていないとき，`Option.none()`をctxにいれるべきところを`undefined`を入れるようにしていたのを修正
- related #867
=> fix: 認証を強制したエンドポイントでトークンが指定されていない場合にOption.none()を返すように

pkg/timeline/adaptor/controller/timeline.ts, pkg/timeline/adaptor/repository/dummy.ts, pkg/timeline/adaptor/repository/prisma.ts, pkg/timeline/adaptor/validator/timeline.ts, pkg/timeline/mod.ts, pkg/timeline/model/repository.ts, pkg/timeline/router.ts, pkg/timeline/service/public.test.ts, pkg/timeline/service/public.ts, resources/schema.json
close #1167 
- I have implemented a public timeline that includes all public posts.
- new endpoint: `GET /v0/timeline/public`
- Filters are same as home timeline endpoint.
- update API schemas
- Refactoring: made the conversion logic for filters and limits in `PrismaRepository` more reusable
=> feat: impl public timeline for all public notes

pkg/accounts/testData/testData.ts
related: https://github.com/pulsate-dev/caramel/issues/381
- アカウントのテスト用ダミーデータのfactoryが同じメールアドレスを返すようになっていたのを修正
- 起こっていたこと:
- caramelのe2eテストとPulsateのテストではアカウント用のダミーデータを`generateDummyAccount()`を使って生成している
- この関数はパスワードとbio，**メールアドレス**を固定値として返すようになっていた
- 本来仕様上はメールアドレスは重複してはならない
- #1212 でログイン仕様が変更されるまで顕在化しなかった
- そのため，e2eテストで正しいメールアドレスを入力しても同じメールアドレスのアカウントが複数あることによってアカウント取得処理が正しく行われず，ログインに失敗していた
=> fix(test): make dummy account data unique
